services:
  taskbench-backend:
    build: .
    image: taskbench/taskbench-backend:dev

  test:
    image: alpine:latest
    command: sh -c "apk add --no-cache netcat-openbsd && nc -zv taskbench-backend 8000"