services:
  taskbench-backend:
    build: .
    image: taskbench/taskbench-backend:dev
    restart: no

  database:
    restart: no

#  test:
#    image: alpine:latest
#    command: sh -c "apk add --no-cache netcat-openbsd && nc -zv taskbench-backend 8000"
#    depends_on:
#      taskbench-backend:
#        condition: service_healthy