services:
  database:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  taskbench-backend:
    image: taskbench/taskbench-backend:latest
    container_name: taskbench-backend
    restart: always
    ports:
      - "8000"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
    healthcheck:
      test: [ "CMD", "test", "-f", "/tmp/app_ready" ]
      interval: 5s
      timeout: 2s
      retries: 10

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./taskbench.crt:/etc/ssl/certs/taskbench.crt:ro
      - ./taskbench.key:/etc/ssl/private/taskbench.key:ro
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - taskbench-backend

volumes:
  postgres_data: