# Generated by Django 5.2 on 2025-04-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbench', '0003_remove_task_status_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
