# Generated by Django 5.2 on 2025-05-19 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbench', '0004_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
